#Render enchantment character overlay
renderEnchOverlay = true
#The height of enchantment character overlay
#Range: -1000000 ~ 1000000
enchOverlayZVal = 250
#Digging Preview
diggingPreview = true

