
["Display Settings"]
	#Show vanilla hearts
	showVanillaHearts = false
	#Show health as decimals or whole numbers
	showDecimalHealth = true
	#Show vanilla armor bar
	showVanillaArmor = false
	#Show vanilla hunger bar
	showVanillaHunger = false
	#Show vanilla oxygen bubbles
	showVanillaOxygen = false
	#Show numeric hunger instead of vanilla hunger bar
	showNumericHunger = true
	#Show custom oxygen icon when underwater
	showOxygenIcon = true
	#Show numeric health instead of vanilla health bar
	showNumericHealth = true
	#Horizontal offset between the health icon and the numeric health text
	#Range: 0 ~ 100
	healthTextOffset = 33
	#Show numeric oxygen value when underwater
	showNumericOxygen = true
	#Show custom health icon
	showHealthIcon = true
	#Show custom armor icon
	showArmorIcon = true
	#Show custom hunger icon
	showHungerIcon = true
	#Enable dynamic health color change (Green -> Full, Yellow -> Low, Red -> Critical)
	enableDynamicHealthColor = true
	#Horizontal position of the health icon display
	#Range: -1000 ~ 1000
	healthDisplayX = -85
	#Vertical position of the health icon display
	#Range: 0 ~ 1000
	healthDisplayY = 43
	#Horizontal position of the armor icon display
	#Range: -1000 ~ 1000
	armorDisplayX = -85
	#Vertical position of the armor icon display
	#Range: 0 ~ 1000
	armorDisplayY = 60
	#Horizontal position of the hunger icon display
	#Range: -1000 ~ 1000
	hungerDisplayX = 70
	#Vertical position of the hunger icon display
	#Range: 0 ~ 1000
	hungerDisplayY = 43
	#Horizontal position of the oxygen icon display
	#Range: -1000 ~ 1000
	oxygenDisplayX = 70
	#Vertical position of the oxygen icon display
	#Range: 0 ~ 1000
	oxygenDisplayY = 60
	#Color of the health numerical value in the HUD. Use's Decimal color code; Default is Red
	#Range: 0 ~ 16777215
	healthColor = 16733525
	#Enable or disable black outline around health numerical values.
	showHealthOutline = false

