
[DoesPotatoTickConfig]

	[DoesPotatoTickConfig."Misc Settings"]
		#If enabled, Does Potato Tick will send a client message to notify the login players about their mob farm.
		Notification = true
		#If enabled, Does Potato Tick will auto-detect the mob farms in your worlds.
		MobFarmDetection = true
		#The least count of entities that enables the current chunk to be detected as a mob farm.
		#Range: > 0
		MobFarmEntitiesCountThreshold = 25
		#The type of entities that will be detected.
		#Do note that all the enemies are always detected no matter what is defined here if you don't disable the DetectEnemies config option below.
		MobFarmTypes = []
		#If enabled, Does Potato Tick will keep tracking if your worlds have mob farms of enemies.
		#Require game restart to take effect.
		DetectEnemies = true

	[DoesPotatoTickConfig."Entity Ticking Settings"]

		[DoesPotatoTickConfig."Entity Ticking Settings"."General Toggle Settings"]
			#Master switch for the entity optimization system. Disable to turn off all optimizations.
			EnableGeneralEntityOptimization = true

		[DoesPotatoTickConfig."Entity Ticking Settings"."Distance Settings"]
			#Maximum vertical chunk distance where entities will continue ticking.
			#Range: > 1
			MaxTickableChunkDistanceInVerticalHeight = 2
			#Maximum horizontal chunk distance where entities will continue ticking.
			#Range: > 1
			MaxTickableChunkDistanceInHorizontalWidth = 4

		[DoesPotatoTickConfig."Entity Ticking Settings"."Only Settings"]
			#Only optimize living entities (excludes items, projectiles, etc.)
			OnlyLivingEntitiesOptimizable = false
			#Only optimize enemies entities.
			OnlyEnemiesOptimizable = false
			#Only optimize animals and passive mobs.
			OnlyAnimalsOptimizable = false
			#Only apply optimization when no raid is active in the current level.
			OnlyOptimizableWhenTheCurrentLevelHasNoRaids = false

		[DoesPotatoTickConfig."Entity Ticking Settings"."Always Tick Settings"]

			[DoesPotatoTickConfig."Entity Ticking Settings"."Always Tick Settings".Entities]

				[DoesPotatoTickConfig."Entity Ticking Settings"."Always Tick Settings".Entities."Fast Ignore"]
					#If true, hostile mobs will ALWAYS tick regardless of distance.
					EnemiesAlwaysTick = false
					#If true, projectiles will ALWAYS tick (arrows, fireballs, etc.).
					ProjectilesAlwaysTick = true
					#If true, entities that are targeted by projectiles will always tick.
					ProjectileTargetsAlwaysTick = true
					#If true, item entities will ALWAYS tick.
					ItemEntitiesAlwaysTick = false
					#If true, raiders will always tick if the current level has an active raid.
					RaidersAlwaysTickWhenTheCurrentLevelHasRaids = true
					#If true, animals will ALWAYS tick regardless of distance.
					AnimalsAlwaysTick = false

				[DoesPotatoTickConfig."Entity Ticking Settings"."Always Tick Settings".Entities.Blacklist]
					#A list of specific entities that will always tick no matter what.
					EntitiesThatWillAlwaysTick = ["minecraft:ender_dragon", "minecraft:ghast", "minecraft:wither", "minecraft:player", "alexsmobs:void_worm", "alexsmobs:void_worm_part", "alexsmobs:spectre", "twilightforest:naga", "twilightforest:lich", "twilightforest:yeti", "twilightforest:snow_queen", "twilightforest:minoshroom", "twilightforest:hydra", "twilightforest:knight_phantom", "twilightforest:ur_ghast", "atum:pharaoh", "mowziesmobs:barako", "mowziesmobs:ferrous_wroughtnaut", "mowziesmobs:frostmaw", "mowziesmobs:naga", "aoa3:skeletron", "aoa3:smash", "aoa3:baroness", "aoa3:clunkhead", "aoa3:corallus", "aoa3:cotton_candor", "aoa3:craexxeus", "aoa3:xxeus", "aoa3:creep", "aoa3:crystocore", "aoa3:dracyon", "aoa3:graw", "aoa3:gyro", "aoa3:hive_king", "aoa3:kajaros", "aoa3:miskel", "aoa3:harkos", "aoa3:raxxan", "aoa3:okazor", "aoa3:king_bambambam", "aoa3:king_shroomus", "aoa3:kror", "aoa3:mechbot", "aoa3:nethengeic_wither", "aoa3:red_guardian", "aoa3:blue_guardian", "aoa3:green_guardian", "aoa3:yellow_guardian", "aoa3:rock_rider", "aoa3:shadowlord", "aoa3:tyrosaur", "aoa3:vinecorne", "aoa3:visualent", "aoa3:voxxulon", "aoa3:bane", "aoa3:elusive", "gaiadimension:malachite_drone", "gaiadimension:malachite_guard", "blue_skies:alchemist", "blue_skies:arachnarch", "blue_skies:starlit_crusher", "blue_skies:summoner", "stalwart_dungeons:awful_ghast", "stalwart_dungeons:nether_keeper", "stalwart_dungeons:shelterer_without_armor", "dungeonsmod:extrapart", "dungeonsmod:king", "dungeonsmod:deserted", "dungeonsmod:crawler", "dungeonsmod:ironslime", "dungeonsmod:kraken", "dungeonsmod:voidmaster", "dungeonsmod:lordskeleton", "dungeonsmod:winterhunter", "dungeonsmod:sun", "forestcraft:beequeen", "forestcraft:iguana_king", "forestcraft:cosmic_fiend", "forestcraft:nether_scourge", "cataclysm:ender_golem", "cataclysm:ender_guardian", "cataclysm:ignis", "cataclysm:ignited_revenant", "cataclysm:netherite_monstrosity", "iceandfire:fire_dragon", "iceandfire:ice_dragon", "iceandfire:lightning_dragon", "iceandfire:dragon_multipart"]
					#All entities from these mod IDs will always tick.
					EntitiesOfTheModsThatWillAlwaysTick = ["create", "witherstormmod", "traveloptics", "irons_spellbooks", "valkyrienskies", "vs_eureka"]
					#A list of raider entities that will always tick.
					RaidersThatWillAlwaysTick = []

			[DoesPotatoTickConfig."Entity Ticking Settings"."Always Tick Settings".Dimensions]
				#A whitelist of dimensions where entity optimization is enabled. Leave empty to allow all.
				OptimizableDimensions = []

