
["Configs for Dreadsteel"]
	#Dreadsteel helmet's armor value (Default = 10)
	"Helmet armor" = 15
	#Dreadsteel chestplate's armor value (Default = 15)
	"Chestplate armor" = 18
	#Dreadsteel leggings's armor value (Default = 12)
	"Leggings armor" = 17
	#Dreadsteel boots' armor value (Default = 9)
	"Boots armor" = 14
	#Dreadsteel armor piece toughness (Default = 8)
	"Armor toughness" = 10
	#Dreadsteel armor piece knockback resistance (Default = 0.25)
	"Armor knockback resistance" = 0.25
	#Dreadsteel Scythe's attack damage. Note that +1 damage comes from your hand so 49 = 50 damage on tootltip (Default = 49)
	"Scythe attack damage" = 49
	#Dreadsteel Scythe's attack speed (Default = 1.6)
	"Scythe attack speed" = 1.6

