
#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

	[types.wood_type]

		[types.wood_type.domum_ornamentum]
			cactus = true
			cactus_extra = true

		[types.wood_type.ars_nouveau]
			archwood = true

		[types.wood_type.quark]
			azalea = true
			ancient = true
			blossom = true

		[types.wood_type.eldritch_end]
			primordial = true

		[types.wood_type.phantasm]
			pream = true

		[types.wood_type.aether]
			skyroot = true

		[types.wood_type.iceandfire]
			dreadwood = true

		[types.wood_type.twilightforest]
			twilight_oak = true
			canopy = true
			mangrove = true
			dark = true
			time = true
			transformation = true
			mining = true
			sorting = true

		[types.wood_type.cataclysm]
			chorus = true

		[types.wood_type.vinery]
			dark_cherry = true

		[types.wood_type.enlightened_end]
			indigo = true
			cerulean = true

		[types.wood_type.outer_end]
			azure = true

		[types.wood_type.alexscaves]
			pewen = true
			thornwood = true

		[types.wood_type.forbidden_arcanus]
			fungyss = true
			aurum = true
			edelwood = true

		[types.wood_type.biomeswevegone]
			aspen = true
			baobab = true
			blue_enchanted = true
			cika = true
			cypress = true
			ebony = true
			fir = true
			florus = true
			green_enchanted = true
			holly = true
			ironwood = true
			jacaranda = true
			mahogany = true
			maple = true
			palm = true
			pine = true
			rainbow_eucalyptus = true
			redwood = true
			sakura = true
			skyris = true
			white_mangrove = true
			willow = true
			witch_hazel = true
			zelkova = true

		[types.wood_type.betterend]
			end_lotus = true
			jellyshroom = true
			lucernia = true
			mossy_glowshroom = true
			pythadendron = true
			dragon_tree = true
			helix_tree = true
			lacugrove = true
			tenanea = true
			umbrella_tree = true

		[types.wood_type.betternether]
			anchor_tree = true
			mushroom_fir = true
			nether_sakura = true
			rubeus = true
			stalagnate = true
			wart = true
			willow = true
			nether_reed = true
			nether_mushroom = true

		[types.wood_type.betterarcheology]
			rotten = true

	[types.leaves_type]

		[types.leaves_type.ars_nouveau]
			blue_archwood = true
			green_archwood = true
			purple_archwood = true
			red_archwood = true

		[types.leaves_type.twilightforest]
			beanstalk = true
			thorn = true
			twilight_oak = true
			canopy = true
			mangrove = true
			dark = true
			rainbow_oak = true
			time = true
			transformation = true
			mining = true
			sorting = true

		[types.leaves_type.eldritch_end]
			primordial = true

		[types.leaves_type.phantasm]
			pream = true

		[types.leaves_type.aether]
			skyroot = true
			golden_oak = true
			crystal = true
			crystal_fruit = true
			holiday = true
			decorated_holiday = true

		[types.leaves_type.vinery]
			grapevine = true
			dark_cherry = true
			apple = true

		[types.leaves_type.outer_end]
			azure = true

		[types.leaves_type.alexscaves]
			ancient = true

		[types.leaves_type.forbidden_arcanus]
			aurum = true
			nuggety_aurum = true

		[types.leaves_type.quark]
			ancient = true
			blue_blossom = true
			lavender_blossom = true
			orange_blossom = true
			yellow_blossom = true
			red_blossom = true

		[types.leaves_type.ars_elemental]
			yellow_archwood = true

		[types.leaves_type.biomeswevegone]
			aspen = true
			baobab = true
			blue_enchanted = true
			cika = true
			cypress = true
			ebony = true
			fir = true
			green_enchanted = true
			holly = true
			ironwood = true
			jacaranda = true
			mahogany = true
			maple = true
			palm = true
			pine = true
			rainbow_eucalyptus = true
			redwood = true
			skyris = true
			white_mangrove = true
			willow = true
			witch_hazel = true
			zelkova = true
			palo_verde = true
			araucaria = true
			ripe_baobab = true
			flowering_baobab = true
			blue_spruce = true
			blooming_witch_hazel = true
			brown_birch = true
			brown_oak = true
			brown_zelkova = true
			ripe_orchard = true
			flowering_orchard = true
			flowering_palo_verde = true
			holly_berry = true
			indigo_jacaranda = true
			flowering_jacaranda = true
			flowering_indigo_jacaranda = true
			yucca = true
			ripe_yucca = true
			flowering_yucca = true
			orange_birch = true
			orange_oak = true
			orange_spruce = true
			orchard = true
			red_birch = true
			red_maple = true
			red_oak = true
			red_spruce = true
			silver_maple = true
			green_apple_skyris = true
			flowering_skyris = true
			flowering_ironwood = true
			white_sakura = true
			yellow_sakura = true
			yellow_birch = true
			yellow_spruce = true
			firecracker = true

		[types.leaves_type.betternether]
			willow = true
			rubeus = true
			anchor_tree = true
			nether_sakura = true

		[types.leaves_type.betterend]
			pythadendron = true
			lacugrove = true
			dragon_tree = true
			tenanea = true
			lucernia = true

#Disables specific entries
[entries]

	[entries.wood_type]

		[entries.wood_type.twilightforest]
			hollow_log_horizontal = true
			hollow_log_vertical = true
			banister = true
			hollow_log_climbable = true

		[entries.wood_type.decorative_blocks]
			beam = true
			support = true
			seat = true
			palisade = true

		[entries.wood_type.woodworks]
			trapped_chest = true
			boards = true
			chest = true
			beehive = true
			bookshelf = true
			chiseled_bookshelf = true
			ladder = true

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.quark]
			hollow_log = true
			vertical_planks = true
			post = true
			trapped_chest = true
			bookshelf = true
			chest = true
			stripped_post = true
			ladder = true
			vertical_slab = true

		[entries.wood_type.twigs]
			table = true

		[entries.wood_type.dramaticdoors]
			short_door = true
			tall_door = true

		[entries.wood_type.storagedrawers]
			trim = true
			full_drawers_2 = true
			half_drawers_1 = true
			full_drawers_4 = true
			half_drawers_4 = true
			half_drawers_2 = true
			full_drawers_1 = true

	[entries.leaves_type]

		[entries.leaves_type.quark]
			hedge = true
			leaf_carpet = true

		[entries.leaves_type.woodworks]
			leaf_pile = true

